export const ACHIEVEMENTS_LIST = [
    {
        id: 0,
        title: 'The journey begins!',
        difficult: 'easy',
        description: 'You added your first country',
        achieved: false,
        emojiId: 'airplane',
    },

    {
        id: 1,
        title: 'Wizard of Oz',
        difficult: 'easy',
        description: 'Took a trip to Australia',
        achieved: false,
        emojiId: 'surfer',
    },
    {
        id: 2,
        title: 'No more worlds to conquer',
        difficult: 'easy',
        description: 'Visited all seven continents',
        achieved: false,
        emojiId: 'v',
    },
    {
        id: 3,
        title: 'Bonne vacance',
        difficult: 'easy',
        description: 'Visited France',
        achieved: false,
        emojiId: 'baguette_bread',
    },
    {
        id: 4,
        title: 'Double digits',
        difficult: 'easy',
        description: 'Added your 10th country',
        achieved: false,
        emojiId: 'keycap_ten',
    },
    {
        id: 5,
        title: 'Twenty Club',
        difficult: 'easy',
        description: 'Visited 20 countries',
        achieved: false,
        emojiId: 'sunglasses',
    },
    {
        id: 6,
        title: 'Half Cenutry',
        difficult: 'easy',
        description: 'Visited 50 countries',
        achieved: false,
        emojiId: 'juggling',
    },
    {
        id: 7,
        title: '100 Club',
        difficult: 'easy',
        description: 'Visited 100 countries',
        achieved: false,
        emojiId: '100',
    },
    {
        id: 8,
        title: 'Scandi-mania',
        difficult: 'easy',
        description: 'Visited every country in Scandinavia',
        achieved: false,
        emojiId: 'passenger_ship',
    },
    {
        id: 9,
        title: 'Travel Blogger',
        difficult: 'easy',
        description: 'You shared your map',
        achieved: false,
        emojiId: 'world_map',
    },
    {
        id: 10,
        title: 'La bella Italia',
        difficult: 'easy',
        description: 'Paid a visit to Italy',
        achieved: false,
        emojiId: 'pizza',
    },
    {
        id: 11,
        title: 'Nocean',
        difficult: 'easy',
        description: 'Visited a landlocked country',
        achieved: false,
        emojiId: 'airplane',
    },
    {
        id: 12,
        title: 'Herculean Effort',
        difficult: 'easy',
        description: 'Took a trip to Greece',
        achieved: false,
        emojiId: 'flag-gr',
    },
    {
        id: 13,
        title: 'The Great Wall',
        difficult: 'easy',
        description: 'You visited China',
        achieved: false,
        emojiId: 'flag-cn',
    },
]
